name: Update WinGet

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-winget:
    runs-on: windows-latest
    steps:
      - name: Submit to WinGet
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Saturate.Ridgeline
          installers-regex: '\.exe$|\.msi$'
          token: ${{ secrets.WINGET_TOKEN }}
